/**
 * Barrel import — importing this file triggers registration of all step definitions.
 * Import it once in your test file (or via a global setup) to activate all registered steps.
 */
import './tv-show-folder-was-imported'
import './tv-show-folder-was-imported-with-no-media-files'
import './tv-show-folder-was-recognized'
import './tv-show-folder-was-recognized-partial'
import './folder-was-selected'
import './rename-button-is-disabled'
import './rename-button-is-clicked'
import './recognize-button-is-clicked'
import './rename-prompt-is-open'
import './cancel-on-rename-prompt'
import './rename-prompt-is-closed'
import './confirm-rename-prompt'
import './confirm-recognize-prompt'
import './rename-confirm-button-is-disabled'
import './recognize-confirm-button-is-disabled'
import './recognize-prompt-shows-not-all-episodes'
import './recognize-hint-icon-is-hovered'
import './recognize-hint-tooltip-is-displayed'
import './search-button-is-clicked'
import './search-database-is-selected'
import './searchbox-input-is-focused'
import './searchbox-shows-error-message-xxx'
import './tv-show-folder-with-tmdb-id-84666-was-imported'
import './start-http-proxy'
